config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'menus#index'
  get 'menu', to: 'menus#getMenu', as: 'get_menu'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
    include MenusHelper
    def index
    end

    def getMenu
        @menu_info = get_menu_info
        render :index
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/menus_helper.rb
require 'open-uri'
require 'nokogiri'
require 'csv'
require 'selenium-webdriver'

module MenusHelper
    def get_menu_info

        driver = Selenium::WebDriver.for :firefox

        driver.navigate.to "http://www.tamagoya.co.jp/menu_list.html"
        latestnews = driver.find_element(:id, "latestnews_txt")
        menu_date = latestnews.find_element(:class, "menutitle_date").text
        menu_details = latestnews.find_element(:class, "menu_list")
        menu_maindish = menu_details.find_element(:class, "menu_maindish").text
        menu_list_data = menu_details.find_elements(:class, "menu_arrow")
        menu_list = []
        menu_list_data.each do |list|
          menu_list.push(list.text)
        end

        driver.quit

        menu_info = {menudate: menu_date, maindish: menu_maindish, menulist: menu_list}

        return menu_info
   end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HungryApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/menus/index.html.erb
今日のメニューは！<br><br>

<%= link_to '見てみる!!', get_menu_path, class: 'btn btn-default' %>
<br><br>
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~<br>
<% if @menu_info != nil %>
  <%= @menu_info[:menudate] %>のMENU!!!!<br>
  <%= @menu_info[:maindish] %><br>
  <% @menu_info[:menulist].each do |menu| %>
    ★<%= menu %><br>
  <% end %>
<% else %>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
<% end %>
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~<br>